field: a53a9f05-dc13-4e76-b462-5b32852541aa
fieldLayouts:
  88c121c6-667f-4281-a11e-fffee0658cf4:
    tabs:
      -
        fields:
          2d0c9d1f-e9da-4552-a35f-86628b41376f:
            required: '0'
            sortOrder: '5'
          6876567c-be47-41de-ac8a-427d631137b7:
            required: '1'
            sortOrder: '1'
          907f1175-cea4-48d9-8c04-16c9a4e4f30f:
            required: '0'
            sortOrder: '3'
          d78b03d5-9323-4e5b-b400-c40a888f6ab8:
            required: '1'
            sortOrder: '2'
          df2d5d4b-e452-49e7-823e-d508911e1f00:
            required: '0'
            sortOrder: '4'
        name: Content
        sortOrder: '1'
fields:
  2d0c9d1f-e9da-4552-a35f-86628b41376f:
    contentColumnType: string
    fieldGroup: null
    handle: statKey
    instructions: 'ID from Deltek'
    name: 'Stat Key'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      mode: readonly
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: mmikkel\incognitofield\fields\IncognitoFieldType
  6876567c-be47-41de-ac8a-427d631137b7:
    contentColumnType: string
    fieldGroup: null
    handle: statFigure
    instructions: ''
    name: Figure
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  907f1175-cea4-48d9-8c04-16c9a4e4f30f:
    contentColumnType: string
    fieldGroup: null
    handle: statFigure2
    instructions: '(Figure 2 and Label 2 are optional. Use only if there are two figures in the stat.)'
    name: 'Figure 2'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d78b03d5-9323-4e5b-b400-c40a888f6ab8:
    contentColumnType: string
    fieldGroup: null
    handle: statLabel
    instructions: ''
    name: Label
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  df2d5d4b-e452-49e7-823e-d508911e1f00:
    contentColumnType: text
    fieldGroup: null
    handle: statLabel2
    instructions: ''
    name: 'Label 2'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: stat
name: Stat
sortOrder: '1'
