fieldLayouts:
  2df2134d-b7ac-4a6d-aa76-f2a0496e8d2a:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 6fbf4208-fbed-4a6c-a92d-9d4ab0b78d71
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a53a9f05-dc13-4e76-b462-5b32852541aa
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: General
        sortOrder: '1'
      -
        elements:
          -
            fieldUid: 8ace18eb-ea90-4bbd-8483-5fc18840ea38
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: '2'
handle: about
hasTitleField: '0'
name: About
section: 8bb717b8-117d-4f60-94fe-371e4464a9dc
sortOrder: '1'
titleFormat: '{section.name|raw}'
