fieldLayouts:
  bf2246e8-2117-4432-bc42-c69a9427157c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 6fbf4208-fbed-4a6c-a92d-9d4ab0b78d71
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: General
        sortOrder: '1'
      -
        elements:
          -
            fieldUid: a53a9f05-dc13-4e76-b462-5b32852541aa
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Media Blocks'
        sortOrder: '2'
      -
        elements:
          -
            fieldUid: 8ace18eb-ea90-4bbd-8483-5fc18840ea38
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: '3'
handle: careers
hasTitleField: '0'
name: Careers
section: f95aaeb3-4081-43fb-894d-e95462a73cf9
sortOrder: '1'
titleFormat: '{section.name|raw}'
