fieldLayouts:
  39b27666-a006-4a52-a9d5-5033dc99366a:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 92a9fada-30bc-4533-a018-ef2866e81063
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 964fede3-6b59-4e22-9af5-7022222156cc
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 85ac77cf-b167-426f-8e7f-010a74e6c539
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d61fa47c-6ab7-4548-a68b-94cc88ff3096
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 95b06449-5529-4942-b840-7eceafbf8e0d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9430edd7-eedb-4754-8bf9-44809625a034
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: eb21c15b-cfd3-452e-9592-8a215bde2b9c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d8d94044-189c-4d03-9c63-8ca76abc8b25
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 46e50c08-5363-4da1-b7c3-77fa247b9032
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c513b03d-8b0c-4184-9e40-9663db54e55c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d16e56d7-1702-46b2-b089-80febb4966c3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0fa3aa7d-8d86-4e04-9dcd-c3977d72e4b0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 18de8a91-8446-4684-9089-ed7f652813fc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 983f8382-dbb5-42ff-b278-ba7dface6d7b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6445822d-589d-4bc6-a651-a09d649d38dd
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 05cee5f0-a7a1-4831-aeeb-7f372591c206
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d7ed6c7a-2b49-4e06-bacb-574f023ffbb1
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Person Info'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 8ace18eb-ea90-4bbd-8483-5fc18840ea38
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: person
hasTitleField: false
name: Person
section: c9d7915e-d21a-4758-8e64-38e16abb4491
sortOrder: 1
titleFormat: '{personFirstName} {personLastName}'
