fieldLayouts:
  6872815c-0c25-4999-a34e-b41c618ba5fc:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 71fce5df-9f25-42f2-981a-96ee9ea36e79
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b28c7e24-eefc-499e-8f00-23b9a5bd893b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 315d247b-1be8-4115-97eb-bcd4978c14a0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d16e56d7-1702-46b2-b089-80febb4966c3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 85ac77cf-b167-426f-8e7f-010a74e6c539
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f548d670-dab4-452a-9078-43040a484575
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 928d5a43-5ca7-4292-9470-70cee4a85b8f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2211b7cd-43db-4b80-869b-432976c22c87
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3455b594-c50a-4516-966a-a3ddd327056f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bd3b79a4-42de-4551-b7c7-339e17a55043
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bd58ad9d-3396-4981-a6e0-ed8312c4ab23
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c158ba5a-ae46-4204-b83d-a47dec6747e7
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2fbef783-6c80-4a39-8752-f256790af1d9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e35511d3-8b9a-44f6-ac20-fe085220ba9e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6838594a-29c6-417c-b3ca-e86cd625bf21
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 561d6473-6a39-488d-8e1c-90eee3bb9d29
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d7ed6c7a-2b49-4e06-bacb-574f023ffbb1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 05cee5f0-a7a1-4831-aeeb-7f372591c206
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Project Info'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: a53a9f05-dc13-4e76-b462-5b32852541aa
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a8e93f2e-4d0b-4b2e-ab2b-94511f8b2ebb
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Media Blocks'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 8ace18eb-ea90-4bbd-8483-5fc18840ea38
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 3
handle: projects
hasTitleField: false
name: Projects
section: 9e08b264-69e4-4e00-a814-65027c6e71bb
sortOrder: 1
titleFormat: '{projectClientName} - {projectName}'
