fieldLayouts:
  c27b3278-93b0-4fbb-8ea8-1171159b49c5:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 664bf192-17d2-4bc9-9b29-9e3f99f90bfb
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: General
        sortOrder: '1'
      -
        elements:
          -
            fieldUid: 8ace18eb-ea90-4bbd-8483-5fc18840ea38
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: '2'
handle: services
hasTitleField: '0'
name: Services
section: 385fc297-e43b-4ac7-bfba-985ac4071e82
sortOrder: '1'
titleFormat: '{section.name|raw}'
