fieldLayouts:
  9b5a9b28-4c7e-4e49-b58d-aa121cfa6096:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: d16e56d7-1702-46b2-b089-80febb4966c3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f91217a9-5e77-45e5-bfb8-074ce761b5ea
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 89ea6ce3-7460-4194-82a2-8b82281a4314
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Market Info'
        sortOrder: 1
handle: markets
name: Markets
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    hasUrls: true
    template: projects/index
    uriFormat: 'markets/{slug}'
structure:
  maxLevels: 2
  uid: 9e846260-d783-4711-835e-fa43d2b46bf6
