fieldLayouts:
  9dccdb02-66b4-4cbc-80d8-5e46d461f8bf:
    tabs:
      -
        fields:
          d16e56d7-1702-46b2-b089-80febb4966c3:
            required: '0'
            sortOrder: '1'
        name: 'People Type Info'
        sortOrder: '1'
handle: peopleTypes
name: 'People Types'
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    hasUrls: '1'
    template: people/index
    uriFormat: 'people/type/{slug}'
structure:
  maxLevels: '1'
  uid: d29cf26e-4039-40e9-8d47-4abdbe46667f
