contentColumnType: text
fieldGroup: 76cf6d8b-6453-4d20-a26b-d31357cdef08
handle: body
instructions: ''
name: Body
searchable: '1'
settings:
  availableTransforms: ''
  availableVolumes: '*'
  columnType: text
  purifierConfig: ''
  purifyHtml: ''
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
