contentColumnType: string
fieldGroup: 76cf6d8b-6453-4d20-a26b-d31357cdef08
handle: email
instructions: ''
name: Email
searchable: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
