contentColumnType: string
fieldGroup: e668eebd-a051-40e2-b807-9cf5252c76fc
handle: impactPublication
instructions: ''
name: Publication
searchable: '1'
settings:
  charLimit: ''
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
