contentColumnType: text
fieldGroup: a3f61274-1914-4acf-8200-363070bab519
handle: locationsDescription
instructions: ''
name: 'Locations Description'
searchable: '1'
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
