contentColumnType: string
fieldGroup: 051a5088-1f13-4554-a13b-943a9cc025ca
handle: officeState
instructions: ''
name: State
searchable: '1'
settings:
  charLimit: ''
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
