contentColumnType: string
fieldGroup: 051a5088-1f13-4554-a13b-943a9cc025ca
handle: officeLeaders
instructions: ''
name: 'Office Leaders'
searchable: '1'
settings:
  contentTable: '{{%matrixcontent_officeleaders}}'
  localizeBlocks: false
  maxBlocks: ''
  minBlocks: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
