contentColumnType: string
fieldGroup: 652bd3c2-ebe8-41fb-9419-5bb52187c6f2
handle: personCertifications
instructions: ''
name: Certifications
searchable: '1'
settings:
  charLimit: ''
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
