contentColumnType: string
fieldGroup: bb82ffa5-12e2-4111-8c1b-383fb2917ab2
handle: projectLeaders
instructions: ''
name: Leaders
searchable: '1'
settings:
  contentTable: '{{%matrixcontent_projectleaders}}'
  localizeBlocks: false
  maxBlocks: ''
  minBlocks: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
