contentColumnType: text
fieldGroup: bb82ffa5-12e2-4111-8c1b-383fb2917ab2
handle: projectTagline
instructions: ''
name: Tagline
searchable: '1'
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
