contentColumnType: string
fieldGroup: 76cf6d8b-6453-4d20-a26b-d31357cdef08
handle: relatedProjects
instructions: 'Manually set related projects. If less than 4 are selected, up to 4 projects related by category, etc., will be automatically selected if possible.'
name: 'Related Projects'
searchable: true
settings:
  limit: '4'
  localizeRelations: false
  selectionLabel: 'Add a Project'
  source: null
  sources:
    - 'section:9e08b264-69e4-4e00-a814-65027c6e71bb'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
