dateModified: 1601139708
email:
  fromEmail: developer@firebellydesign.com
  fromName: 'Affiliated Engineers'
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.webfaction.com
    password: 'VYRRyW4s%NRbmNMwer)ry[4HxRaE4R'
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: aei_www
  transportType: craft\mail\transportadapters\Smtp
plugins:
  aei:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      deltekActiveImportSections:
        Awards: '1'
        Impact: '1'
        Offices: '1'
        People: '1'
        Projects: '1'
  assetrev:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  ckeditor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  command-palette:
    enabled: '1'
    licenseKey: null
    schemaVersion: 3.0.0
    settings: null
  constant-contact:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  cp-css:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.0.0
    settings:
      additionalCss: ".redactor-styles a.button,\r\n.redactor-styles .button-block a {\r\n  padding: 11px 20px;\r\n  display: inline-block;\r\n  border: 1px solid #282826;\r\n  color: #282826;\r\n  border-radius: 3px;\r\n  text-decoration: none;\r\n}\r\n.redactor-styles a.button:hover,\r\n.redactor-styles .button-block a:hover {\r\n  color: #fff;\r\n  text-decoration: none;\r\n  background: #282826;\r\n}\r\n"
      cssFile: ''
  cp-field-inspect:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  expanded-singles:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  fb-utils:
    enabled: '0'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  google-tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
    settings:
      containerID: GTM-PZLP2FR
  imager:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.0.0
    settings: null
  incognito-field:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.1.1
    settings: null
  poptin:
    client_id: ''
    edition: standard
    enabled: false
    login_url: ''
    poptin_url: 'https://app.popt.in'
    schemaVersion: 1.0.0
    token: ''
    user_id: ''
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
  redactor-tweaks:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redirect:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.5
    settings:
      catchAllActive: true
      catchAllTemplate: 404.html
      redirectsActive: true
  seo:
    enabled: '1'
    licenseKey: null
    schemaVersion: 3.1.1
    settings:
      description: ''
      facebookAppId: '323796168167088'
      metaTemplate: partials/_seo
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\nSitemap: {{ url(seo.sitemapName ~ \".xml\") }}\n\n{# Disallows #}\n{% if craft.app.config.general.devMode %}\n\n{# Disallow access to everything when in devMode #}\nUser-agent: *\nDisallow: /\n\n{% else %}\n\n{# Disallow access to cpresources/ when live #}\nUser-agent: *\nDisallow: /cpresources/\n\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage:
        - '2151080'
      title:
        -
          key: '1'
          locked: '0'
          template: '{title}'
      titleSuffix: '| Affiliated Engineers'
      twitterHandle: AEITweets
  similar:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  sprout-active:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.0.0
    settings: null
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  wordsmith:
    enabled: '1'
    licenseKey: null
    schemaVersion: 0.0.0.0
    settings: null
system:
  edition: pro
  live: true
  name: 'Affiliated Engineers'
  schemaVersion: 3.5.13
  timeZone: America/Chicago
