field: 0e1b852f-d478-4286-a3f6-c1af971a7e86
fieldLayouts:
  e792890d-8139-457e-a8f4-829f7ee80e6e:
    tabs:
      -
        fields:
          9afe4056-4e75-4333-9f6d-0bfdadc850a4:
            required: false
            sortOrder: 1
          c80ca8b2-04f1-4a3a-97ff-c76b08309d92:
            required: false
            sortOrder: 5
          c854dfc3-a871-449a-af76-f17f427d9e96:
            required: false
            sortOrder: 4
          e624582e-e415-42c1-aa79-87faee527edf:
            required: false
            sortOrder: 3
          e658599b-f187-4710-916e-bca7d52f3d96:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  9afe4056-4e75-4333-9f6d-0bfdadc850a4:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c80ca8b2-04f1-4a3a-97ff-c76b08309d92:
    contentColumnType: string
    fieldGroup: null
    handle: quoteKey
    instructions: 'ID from Deltek'
    name: 'Quote Key'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      mode: readonly
      modeOverride: null
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: mmikkel\incognitofield\fields\IncognitoFieldType
  c854dfc3-a871-449a-af76-f17f427d9e96:
    contentColumnType: string
    fieldGroup: null
    handle: personCompany
    instructions: ''
    name: Company
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e624582e-e415-42c1-aa79-87faee527edf:
    contentColumnType: string
    fieldGroup: null
    handle: personName
    instructions: 'Use this if not an AEI Person'
    name: Name
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e658599b-f187-4710-916e-bca7d52f3d96:
    contentColumnType: string
    fieldGroup: null
    handle: aeiPerson
    instructions: ''
    name: 'AEI Person'
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add a Person'
      source: null
      sources:
        - 'section:c9d7915e-d21a-4758-8e64-38e16abb4491'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
