field: 94380646-eb39-4b58-b069-75e4e23a980e
fieldLayouts:
  fed2423f-155b-454e-97c0-c0d7b972fbf8:
    tabs:
      -
        fields:
          05314f82-3231-4e9d-93c9-c50c2766598a:
            required: '0'
            sortOrder: '2'
          282d9252-879c-46e2-97a6-a99971221ab7:
            required: '0'
            sortOrder: '3'
          5f19f594-494d-4974-acc4-794cc3a4abb4:
            required: '0'
            sortOrder: '1'
          7e1009a2-83b9-404c-baf3-6ba6ea19672e:
            required: '0'
            sortOrder: '4'
          8afe16e6-9150-44b0-9235-f1b3e8669a73:
            required: '0'
            sortOrder: '5'
        name: Content
        sortOrder: '1'
fields:
  05314f82-3231-4e9d-93c9-c50c2766598a:
    contentColumnType: string
    fieldGroup: null
    handle: aeiPerson
    instructions: ''
    name: 'AEI Person'
    searchable: '1'
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add a Person'
      source: null
      sources:
        - 'section:c9d7915e-d21a-4758-8e64-38e16abb4491'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  282d9252-879c-46e2-97a6-a99971221ab7:
    contentColumnType: string
    fieldGroup: null
    handle: personName
    instructions: 'Use this if not an AEI Person'
    name: Name
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5f19f594-494d-4974-acc4-794cc3a4abb4:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7e1009a2-83b9-404c-baf3-6ba6ea19672e:
    contentColumnType: string
    fieldGroup: null
    handle: personCompany
    instructions: ''
    name: 'Company or Title'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8afe16e6-9150-44b0-9235-f1b3e8669a73:
    contentColumnType: string
    fieldGroup: null
    handle: quoteKey
    instructions: 'ID from Deltek'
    name: 'Quote Key'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      mode: readonly
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: mmikkel\incognitofield\fields\IncognitoFieldType
