field: 42705e68-a626-47f8-9b75-6bcb68d1897f
fieldLayouts:
  72df97ec-4719-4f8e-bb1e-df8912726ff6:
    tabs:
      -
        fields:
          3a1a9639-db98-40a5-8c70-195ad94e5656:
            required: '0'
            sortOrder: '6'
          65affc8e-6f29-4b1d-8578-afb85d9e0501:
            required: '0'
            sortOrder: '5'
          81e5b287-264a-4e7f-a154-7c78d26231a8:
            required: '0'
            sortOrder: '2'
          8838cc4a-91fb-4d83-9856-884f5736e932:
            required: '0'
            sortOrder: '3'
          b4eaddc8-8c6a-4143-a65d-4fa3bf309eb0:
            required: '1'
            sortOrder: '1'
          e63021d9-b707-4d9a-82d2-5fb901b5f545:
            required: '0'
            sortOrder: '4'
        name: Content
        sortOrder: '1'
fields:
  3a1a9639-db98-40a5-8c70-195ad94e5656:
    contentColumnType: boolean
    fieldGroup: null
    handle: openInNewWindow
    instructions: ''
    name: 'Open In New Window'
    searchable: '1'
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  65affc8e-6f29-4b1d-8578-afb85d9e0501:
    contentColumnType: string
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: 'Read More'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  81e5b287-264a-4e7f-a154-7c78d26231a8:
    contentColumnType: string
    fieldGroup: null
    handle: relatedEntry
    instructions: ''
    name: 'Related Entry'
    searchable: '1'
    settings:
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources:
        - 'section:66b9cee3-6c4a-4348-8f68-fe1d1bb454a0'
        - 'section:a4b6c9cb-9057-44aa-ba5d-308dcfb5eb62'
        - 'section:c9d7915e-d21a-4758-8e64-38e16abb4491'
        - 'section:9e08b264-69e4-4e00-a814-65027c6e71bb'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  8838cc4a-91fb-4d83-9856-884f5736e932:
    contentColumnType: string
    fieldGroup: null
    handle: linkTitle
    instructions: 'Use this if not a Related Entry'
    name: 'Link Title'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: 'Connect with us on Twitter'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b4eaddc8-8c6a-4143-a65d-4fa3bf309eb0:
    contentColumnType: string
    fieldGroup: null
    handle: linkHeader
    instructions: ''
    name: 'Link Header'
    searchable: '1'
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: Twitter
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e63021d9-b707-4d9a-82d2-5fb901b5f545:
    contentColumnType: string
    fieldGroup: null
    handle: buttonUrl
    instructions: 'Will use Related Entry URL if set'
    name: 'Button URL'
    searchable: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
