fieldLayouts:
  f016cf18-ca46-4ab3-b7e9-e1e4f2877448:
    tabs:
      -
        elements:
          -
            fieldUid: 3d3b557b-1e44-4d69-a3b3-f82fdc7edcd8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d0ad4646-45ed-4db5-a024-6eb2cfcdaa2a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 983f8382-dbb5-42ff-b278-ba7dface6d7b
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global Site Info'
        sortOrder: 1
handle: siteSettings
name: 'Site Settings'
