enableVersioning: true
handle: aboutPages
name: 'About Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    enabledByDefault: true
    hasUrls: true
    template: about/_page.html
    uriFormat: 'about/{slug}'
structure:
  maxLevels: 1
  uid: 0ff22aec-21c4-4a77-903f-57464b8ed9d7
type: structure
