enableVersioning: true
handle: careers
name: Careers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    enabledByDefault: true
    hasUrls: true
    template: about/careers/index
    uriFormat: about/careers
type: single
