enableVersioning: '0'
handle: impact
name: 'News & Insights'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    enabledByDefault: '1'
    hasUrls: '1'
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
