enableVersioning: false
handle: projects
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: 'markets/project/{slug}'
structure:
  maxLevels: 1
  uid: a2938c06-4341-42df-8303-c01afa0458b2
type: structure
