enableVersioning: false
handle: services
name: Services
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    enabledByDefault: true
    hasUrls: true
    template: services/index
    uriFormat: services
type: single
