enableVersioning: '0'
handle: stats
name: Stats
propagationMethod: all
siteSettings:
  fbde05ad-97ce-4076-85e8-261874a1582b:
    enabledByDefault: '1'
    hasUrls: '0'
    template: null
    uriFormat: null
structure:
  maxLevels: '1'
  uid: ce4345ac-40d0-4f47-8010-107515d6a661
type: structure
